# 外置开发环境配置
server:
  port: 5000

spring:
  # 数据源配置 - 使用新的MySQL端口
  datasource:
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/easy-jmeter?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useUnicode=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  # 启用数据库自动初始化
  sql:
    init:
      mode: never

  data:
    mongodb:
      database: easyJmeter
      host: localhost
      port: 27018
      username: root
      password: mongo2020
      authentication-database: admin
  influx:
    url: http://localhost:8087
    user: root
    password: root
    database: easyJmeter

# 开启权限拦截
auth:
  enabled: true

# 开启登录要求验证码
login-captcha:
  enabled: false
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启http请求日志记录
request-log:
  enabled: true

logging:
  level:
    web: debug
    io.github.guojiaxing1995.easyJmeter.mapper: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

minio:
  endpoint: http://localhost:9001
  bucketName: dev
  accessKey: root
  secretKey: minio2023

swagger:
  enable: true

socket:
  server:
    host: 0.0.0.0
    port: 9006
    enable: true
  client:
    serverUrl: http://127.0.0.1:9006
    enable: false

cron:
  heartBeat: "0 0/1 * * * ?"
  deleteTaskRecordStorage: "0 0 1 ? * MON"
  recordStatistics: "0 0/30 * * * ? "
  jmeterLogClear: "0 0 2 ? * *"

mybatis-plus:
  configuration:
  
    # 指定默认枚举类型的类型转换器
  default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    # 开启下划线转驼峰
  map-underscore-to-camel-case: true

  global-config:
    # 开启/关闭 banner 打印
    banner: false
    db-config:
      
      logic-not-delete-value: 'NULL'  # 未删除标记
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml

  type-enums-package: io.github.guojiaxing1995.easyJmeter.common.enumeration
  


lin:
  cms:
    # 开启行为日志记录（logger）
    logger-enabled: true
    # access token 过期时间，3600s 一个小时
    token-access-expire: 3600
    # refresh token 过期时间，2592000s 一个月
    token-refresh-expire: 2592000
    # 令牌 secret
    token-secret: x88Wf0991079889x8796a0Ac68f9ecJJU17c5Vbe8beod7d8d3e695*4



