#主配置文件

spring:
  application:
    name: easy-jmeter
  # 激活环境配置
  profiles:
    active: dev
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  main:
    # 允许 bean 定义覆盖
    allow-bean-definition-overriding: true
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 关闭默认静态资源的映射规则
      add-mappings: false

mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
  type-enums-package: io.github.guojiaxing1995.easyJmeter.common.enumeration
  global-config:
    # 开启/关闭 banner 打印
    banner: false
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml


lin:
  cms:
    # 开启行为日志记录（logger）
    logger-enabled: true
    # access token 过期时间，3600s 一个小时
    token-access-expire: 3600
    # refresh token 过期时间，2592000s 一个月
    token-refresh-expire: 2592000
    # 令牌 secret
    token-secret: x88Wf0991079889x8796a0Ac68f9ecJJU17c5Vbe8beod7d8d3e695*4
logging:
  logback:
    rollingpolicy:
      max-history:
  config:

# SocketIO 配置
socket:
  server:
    host: 0.0.0.0
    port: 9006
    enable: true
  client:
    serverUrl: http://127.0.0.1:9006
    enable: false

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 接口文档
  try-host: http://localhost:${server.port}